### PR TITLE
IBX-869: Fixed loading of mutations schema

### PR DESCRIPTION
**Pull request by bdunogier**
Question | Answer
-- | --
JIRA issue | https://issues.ibexa.co/browse/IBX-869
Type | bugfix
Target Ibexa DXP version | v4.2.x
BC breaks | maybe (custom mutations may have to be updated in the same way)

The schema mutation type is set by detecting what files were generated. When https://github.com/ezsystems/ezplatform-graphql/pull/90 was merged, `DomainContentMutation.types.yaml` was renamed to `ItemMutation.types.yaml`, but the `YamlSchemaProvider` that searches for the files was not updated.

In addition, in v0.14 of overblog/graphql-bundle, the `mutation` function, used to resolve mutations, has been changed. The arguments are not provided as an array anymore, but as regular function arguments. This is the reason for the [error @mnocon found](https://github.com/ibexa/graphql/pull/27#pullrequestreview-891197235). The behaviour had been changed earlier (in v0.13 as far as I can see) but had a compatibility layer that was removed in v0.14.

Note that the `query` function, that replaces the `resolve` one, has undergone the same change, and we will need to update it as well.

### CODE REVIEW

**Review by konradoboza — APPROVED** [review]

**Review by adamwojs — APPROVED** [review]

**Review by mnocon — CHANGES_REQUESTED** [review]
This one fails after https://github.com/ibexa/graphql/pull/26 has been merged.

When I try to execute a mutation like:
```
mutation createFolder {
  createFolder(
    language: eng_GB
    parentLocationId: 2
    input: {
      name: "New Folder"
    }
  ) {
    id
  }
}
```
Then the server response looks like this:
```
{
  "errors": [
    {
      "debugMessage": "Too few arguments to function Ibexa\\GraphQL\\Resolver\\DomainContentMutationResolver::createDomainContent(), 1 passed in /Users/mareknocon/Desktop/Sites/v3_4/vendor/overblog/graphql-bundle/src/Resolver/AbstractProxyResolver.php on line 36 and exactly 4 expected",
      "message": "Internal server Error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createFolder"
      ],
      "trace": [
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/overblog/graphql-bundle/src/Resolver/AbstractProxyResolver.php",
          "line": 36,
          "call": "Ibexa\\GraphQL\\Resolver\\DomainContentMutationResolver::createDomainContent(array(4))"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/overblog/graphql-bundle/src/Definition/GraphQLServices.php",
          "line": 34,
          "call": "Overblog\\GraphQLBundle\\Resolver\\AbstractProxyResolver::resolve(array(2))"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/var/cache/behat/overblog/graphql-bundle/__definitions__/ItemMutationType.php",
          "line": 136,
          "call": "Overblog\\GraphQLBundle\\Definition\\GraphQLServices::mutation('CreateDomainContent', array(4))"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/overblog/graphql-bundle/src/Definition/ArgumentFactory.php",
          "line": 37,
          "call": "Overblog\\GraphQLBundle\\__DEFINITIONS__\\ItemMutationType::Overblog\\GraphQLBundle\\__DEFINITIONS__\\{closure}(null, instance of Overblog\\GraphQLBundle\\Definition\\Argument(3), instance of ArrayObject(2), instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 623,
          "call": "Overblog\\GraphQLBundle\\Definition\\ArgumentFactory::Overblog\\GraphQLBundle\\Definition\\{closure}(null, array(3), instance of ArrayObject(2), instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 550,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveFieldValueOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, null, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 474,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: ItemMutation, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 857,
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'createFolder')"
        },
        {
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'createFolder')"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 859,
          "function": "array_reduce(array(1), instance of Closure, array(0))"
        },
(...)
```

**Comment by adamwojs** [comment]
@bdunogier Have you addressed @mnocon feedback ?

**Comment by bdunogier** [comment]
Yes @adamwojs, this is what the 2nd commit does.

**Comment by mnocon** [comment]
Thanks Bertrand, I've added it to our QA queue

**Comment by micszo** [comment]
Current status.
Create & Update works.
Delete throws exception.

**Comment by bdunogier** [comment]
Pushed an extra change that fixes the arguments for the few remaining mutations. I have only tested `deleteContent`, not the other ones (`uploadFiles` and `createToken`).

**Comment by micszo** [comment]
Current status.

create content OK
update content OK
delete content OK
login / createToken OK
create image / file upload NOK

Exception:
```
"debugMessage": "Call to undefined method Ibexa\\Core\\Repository\\Values\\Content\\Content::getContentInfo()",
      "message": "Internal server Error",
```

**Comment by bdunogier** [comment]
Note that I’m getting a different error (arguments exception) on `uploadFiles`.

**Review by micszo — APPROVED** [review]
QA Approved on Ibexa Commerce 4.2.4-dev.

There's green light for handling file upload separately, ticket will be created shortly.

**Comment by micszo** [comment]
New ticket: https://issues.ibexa.co/browse/IBX-4415.
